Bug report from John (EBo) David...
>>There are a number of places in the Class def which initializes variables which are not const nor static (they are changed internally). These are similar to:
>>
>>sketch_feb17a.ino:79: error: ISO C++ forbids initialization of member 'next_pid'
>>sketch_feb17a.ino:79: error: making 'next_pid' static
>>sketch_feb17a.ino:79: error: ISO C++ forbids in-class initialization of non-const static member 'next_pid'
>>
>>Once I moved the instantiation down into the constructor, it compiled as expected on the Arduino-Due, but not the Mega2560 -- where I got a "sketch_feb17a.ino:862: error: ?bzero? was not declared in this scope"
>>
>>Hope this helps.

Yes... yes it does... I've only run this on the Teensy3.0/3.1 thus far. So thank you for taking the time to submit a bug. I have replaced all the bzero() calls with memset() calls, which is probably the more-portable thing to do. Also cleaned up some sloppiness that you were noticing. Scheduler compiles without warnings now.